---
- name: creacion de grupos
  ansible.builtin.group:
    name: "{{ group_input_name }}"
    state: present

- name: creacion de usuarios
  ansible.builtin.user:
    name: "{{ user_input_name }}"
    group: "{{ group_input_name }}"
    state: present
    shell: /bin/bash
    password: "{{ user_password }}"
  with_items: "{{ users }}"